### PR TITLE
Set up

### PR DESCRIPTION
**Pull request by Haywayaheadshot**
# What?
- Rails app with API.

# Why?
- To connect it to this [front end](https://github.com/Haywayaheadshot/hello-react-front-end) app created with react.

# How?
- Created a new Rails API app called 'hello-rails-back-end'.
- Initialized my project with Git.
- Made sure that my project has a Postgres database set up.
- Created a table for storing mymessages and created 5 different greetings.
- Created an API endpoint that selects a random greeting from my table.

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @Haywayaheadshot 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the readme for the frontend sections:  future feature, MIT link, and all other necessary sections  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Haywayaheadshot** [comment]
@Davidosky007 Thank you for reviewing my code. Sorry for the mix up. I mistakenly hid the other sections under the details section in Tech stack container. I have fixed it for the frontend repo

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @Haywayaheadshot 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git -Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Set up a "Hello world" project with two apps.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
@Abenezer-Tilahun Thank you for reviewing my project. Have a nice day

**Pull request merged**
